typography_spectrum: 0.88614
color:
  brandColors:
    - '#17171a'
    - '#f9f9f9'
    - '#505356'
    - '#80858a'
    - '#c6c6c6'
  brandStrength: 0.5625
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26642
analytics:
  google: null
  facebook: null
  twitter: null
name: TeamImpact
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Team !mpact
description: Kinetic Code
purpose: []
